routes/web.php
<?php

Route::get('media/genre/{id}', 'GenreController@products');
Route::get('artists', 'UserController@artists');
Route::get('produsers', 'UserController@produsers');
Route::get('top-voters', 'UserController@topVoters');
Route::get('media', 'MediaController@index');
Route::get('/', 'MediaController@index');
Auth::routes();
Route::get('search', 'UserController@search');
Route::get('media-search', 'MediaController@search');
Route::get('likes', 'MediaController@likes');
Route::post('edit', 'UserController@edit');
Route::get('edit', 'UserController@editProfile');

Route::group(['middleware' => 'auth'], function () {
    Route::get('favorites', 'UserController@favoritesList');
    Route::get('users/{id}', 'UserController@show');
    Route::get('my-account', 'UserController@myAccount');
    Route::get('activity', 'UserController@activity');
    Route::get('media/create', 'MediaController@create');
    Route::get('media/{media}/edit', 'MediaController@edit');
    Route::post('media', 'MediaController@store');
    Route::patch('media/{media}', 'MediaController@update');
    Route::delete('media/{media}', 'MediaController@destroy');
    Route::get('my-media', 'UserController@myMedia');
    Route::get('unread', 'UserController@unreadMessage');
    Route::get('{relation}/{id}/{action}', 'UserController@sync');
    Route::post('users/{user}/send-message', 'UserController@sendMessage');

});

Route::get('/avatar', function () {
    return view('/users/avatar');
});


Route::get('media/{id}', 'MediaController@show');

app/Models/User.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\Auth;

class User extends Authenticatable
{
    use Notifiable, SoftDeletes;
    protected $fillable = [
        'name',
        'email',
        'password',
        'gender',
        'birthday',
        'twitter',
        'facebook',
        'instagram',
        'role',
        'country',
        'state',
        'city',
        'address',
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $dates = ['birthday', 'created_at', 'updated_at', 'deleted_at'];

    public function media()
    {
        return $this->hasMany(Media::class);
    }

    public function sender()
    {
        return $this->belongsToMany(User::class, 'messages', 'sender_id', 'resiver_id');
    }

    public function resiver()
    {
        return $this->belongsToMany(User::class, 'messages', 'resiver_id', 'sender_id');
    }

    public function listMessages($user_id)
    {
      return $this->belongsToMany(User::class, 'messages', 'resiver_id', 'sender_id')
        ->orWherePivot('sender_id', '=', $user_id)
        ->orWherePivot('resiver_id', '=', $user_id)
        ->withPivot('text')
        ->groupBy('resiver_id')
        ->withTimestamps();
    }

    public function messages($sender_id, $resiver_id)
    {
        return $this->belongsToMany(User::class, 'messages', 'resiver_id', 'sender_id')
            ->wherePivot('sender_id', '=', $resiver_id)
            ->orWherePivot('resiver_id', '=', $resiver_id)
            ->wherePivot('sender_id', '=', $sender_id)
            ->withPivot('text')
            ->withTimestamps();
    }

    public function updateMessages($resiver_id)
    {
        return $this->belongsToMany(User::class, 'messages', 'sender_id', 'resiver_id')
            ->wherePivot('read_at', '=', null)
            ->updateExistingPivot($resiver_id, ['read_at' => Carbon::now()]);
    }

    public function followers()
    {
        return $this->belongsToMany(User::class, 'followers', 'follower_id', 'following_id');
    }

    public function followingers()
    {
        return $this->belongsToMany(User::class, 'followers', 'following_id', 'follower_id');
    }

    public function votes()
    {
        return $this->belongsToMany(Media::class, 'votes')->withTimestamps()->withPivot('date_likes');
    }

    public function todayVotes()
    {
        return $this->belongsToMany(Media::class, 'votes')->withTimestamps()->withPivot('date_likes')
            ->wherePivot('date_likes', '=', Carbon::now()->format('Y-m-d'));
    }

    public function favorites()
    {
        return $this->belongsToMany(Media::class, 'favorites');
    }

    public function scopeEntity($q, string $entity)
    {
        if ($entity == 'artists') {
            return $this->scopeArtists($q);
        }
        return $this->scopeProdusers($q);
    }

    private function scopeArtists($q)
    {
        return $q->whereRole('artist')->withCount('media')->withCount('followers');
    }

    private function scopeProdusers($q)
    {
        return $q->whereRole('produser')->withCount('media')->withCount('followers');
    }
}

app/Http/Controllers/GenreController.php
<?php

namespace App\Http\Controllers;

use App\Models\Genre;

class GenreController extends Controller
{
    public function products(int $id)
    {
        $media = Genre::query()->find($id)->media()->withCount('votes')->paginate(6);
        $genre = Genre::query()->pluck('name', 'id');
        return view('media.index', compact('media', 'genre'));
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\Genre;
use App\Models\Media;
use App\Models\Notification;
use App\Models\User;
use App\Notifications\FavoriteMedia;
use App\Notifications\FollowFromUser;
use App\Notifications\VoteUser;
use Carbon\Carbon;
use GuzzleHttp\Psr7\Response;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Auth\RegisterController;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->only(['favorites', 'myAccount', 'activity']);
    }

    public function artists()
    {
        $users = User::entity('artists')->paginate(6);
        return view('users.index', compact('users'));
    }

    public function produsers()
    {
        $users = User::entity('produsers')->paginate(6);
        return view('users.index', compact('users'));
    }

    public function show(int $id)
    {
        $user = User::query()->withCount('media', 'followers', 'followingers', 'votes')->find($id);
        $messages = $user->messages($user->id, Auth::user()->id)
            ->selectRaw('messages.sender_id, messages.resiver_id, users.name, messages.text, messages.created_at')
            ->orderBy('messages.created_at', 'desc')->get();
        $user->updateMessages(Auth::user()->id);
        return view('users.show', compact('user', 'messages'));
    }

    public function favoritesList()
    {
        $genre = Genre::query()->pluck('name', 'id');
        $media = Auth::user()->favorites()->withCount('votes')->paginate(6);
        return view('media.index', compact('media', 'genre'));
    }

    public function myAccount()
    {
        $user = Auth::user()->with(['media'])->withCount(['followers', 'followingers', 'votes'])
            ->find(Auth::user()->id);
        $media = Media::query()->where('approved', '1')->withCount('votes')->orderBy('created_at', 'desc')->paginate(6);
        return view('users.my-account', compact('user', 'media'));
    }

    public function activity()
    {
        $user = Auth::user()->with(['media'])->withCount(['followers', 'followingers', 'votes'])
            ->find(Auth::user()->id);
        $notifications = Notification::query()->where('created_at', '>=', Carbon::yesterday())
            ->orderBy('created_at', 'desc')->paginate(20);
        return view('users.activity', compact('user', 'notifications'));
    }

    public function search(Request $request)
    {
        $users = User::query()->where('name', 'like', "%{$request->search}%")
            ->withCount('media')->withCount('followers')->paginate(6);
        return view('users.index', compact('users'));
    }

    public function sync(string $relation, int $id, string $action = 'attach')
    {
        $action == 'attach' ? Auth::user()->$relation()->attach($id) : Auth::user()->$relation()->detach($id);
        $this->sendNotify($relation, $id, $action);
        return redirect()->back();
    }

    private function sendNotify($relation, $id, $action)
    {
        switch ($relation) {
            case 'votes':
                Auth::user()->notify(new VoteUser(Media::query()->find($id), $action));
                break;
            case 'followingers':
                Auth::user()->notify(new FollowFromUser(User::query()->find($id), $action));
                break;
            case 'favorites':
                Auth::user()->notify(new FavoriteMedia(Media::query()->find($id), $action));
                break;
        }
    }

    public function myMedia()
    {
        $media = Auth::user()->media()->paginate(10);
        $user = Auth::user()->with(['media'])->withCount(['followers', 'followingers', 'votes'])
            ->find(Auth::user()->id);
        return view('users.my-media', compact('user', 'media'));
    }

    public function topVoters(Request $request)
    {
        $date = self::getDate($request->top);
        $users = User::query()->withCount(['votes' => function ($q) use ($date) {
            if (!is_null($date)) {
                $q->where('votes.created_at', '>=', $date)
                    ->where('votes.created_at', '<=', Carbon::now());
            }
        }])->orderBy('votes_count', 'desc')->paginate(6);
        return view('users.top-voters', compact('users'));
    }

    /**
     * @param $top
     * @return null|Carbon
     */
    public static function getDate($top)
    {
        $date = null;
        if (!empty($top)) {
            if ($top == 'day') {
                $date = Carbon::now()->subDay();
            }
            if ($top == 'week') {
                $date = Carbon::now()->subDays(7);
            }
            if ($top == 'month') {
                $date = Carbon::now()->subDays(31);
            }
        }
        return $date;
    }

    /**
     * @param Request $request
     * @param User $user - resiver
     */
    public function sendMessage(Request $request, User $user)
    {
        Auth::user()->sender()->attach([$user->id => ['text' => $request->text, 'created_at' => Carbon::now()]]);
        return back();
    }

    protected function unreadMessage()
    {
//        $messages_new = Auth::user()->resiver()
//            ->selectRaw('count(messages.sender_id) as mysum')
//            ->wherePivot('read_at', '=', null)->orderBy('mysum', 'desc')
//            ->groupBy('messages.sender_id')->paginate(10);

        $user_id = Auth::user()->id;
        $messages = DB::select(
            "SELECT
              messages.sender_id,
              messages.resiver_id,
              messages.text,
              messages.created_at,
              if(resiver.id = $user_id, sender.name, resiver.name) as recive_name,
              if(resiver.id = $user_id, sender.id, resiver.id) as recive_id,
              sum(if(IFNULL(read_at, 1) = 1, 1, 0)) as count_not_read
            FROM messages RIGHT JOIN users resiver ON messages.resiver_id = resiver.id RIGHT JOIN users sender ON messages.sender_id = sender.id
            WHERE messages.resiver_id = $user_id OR messages.sender_id = $user_id
            GROUP BY recive_id
            ORDER BY messages.created_at DESC"
        );
//          dd($messages);
        return view('users.messages', compact('messages_new', 'messages'));
    }

    /**
     * Edit avatar
     *
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function edit(Request $request)
    {
        $media = Auth::user()->media()->paginate(10);
        if (Hash::check($request['last_password'], Auth::user()->password)) {
            if ($request['password'] == "" || $request['password'] == null) {
                User::query()->where('id', Auth::user()->id)->update($request->except('_token', 'last_password', 'password_confirmation','password'));
                $user = User::query()->where('id', Auth::user()->id)->get();
                return view('users.my-account', compact('user', 'media'));
            }
            else
            {
                $password=bcrypt($request['password']);
                User::query()->where('id', Auth::user()->id)->update($request->except('_token','password', 'last_password', 'password_confirmation','password'));
                User::query()->where('id', Auth::user()->id)->update(['password'=>$password]);
                                $user = User::query()->where('id', Auth::user()->id)->get();
                return view('users.my-account', compact('user', 'media'));
            }
        }
        return ('default value');

    }

    public function editProfile()
    {
        $user = Auth::user();
        $user->select(DB::raw('DATE_FORMAT(birthday, "%Y/%d/%m") as time'))->get();
        $user->save();
        return view('users.edit', compact('user'));
    }

    /**
     * Edit avatar
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    protected function uploadAvatar(Request $request)
    {
        $avatar = RegisterController::upload($request, 'public/avatars');
        Auth::user()->update(['avatar' => $avatar]);
        return view('users.my-account', compact('user'));
    }
}

resources/views/users/activity.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="title-page">
          ACTIVITY
        </div>
      </div>
    </div>
    <div class="row">
      @include('includes.auth-userdata')
      <div class="col-md-8">
        @include('includes.tab-menu')
      @foreach($notifications as $notification)
          @include('notifications.'. snake_case(class_basename($notification->type)))
        @endforeach
        {{ $notifications->links() }}
      </div>
    </div>
  </div>
@endsection

resources/views/users/avatar.blade.php
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
</head>
<div class="container">

    <div class="col-md-8 col-md-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">Avatar</div>
            <div class="panel-body">
                <form method="POST" action="{{ route('upload_file') }}" enctype="multipart/form-data">
                    <input type="file" multiple name="file[]">
                    <input type="hidden" name="id" value="60">
                    <br>
                    <div class="col-md-5"></div>
                    <div class="col-md-7">
                        <button class=" btn btn-primary" type="submit">Upload</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <?php ?>
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Register</div>
                    <div class="panel-body">
                        <form class="form-horizontal" role="form" method="POST" action="/edit">
                            {{ csrf_field() }}

                            <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                                <label for="name" class="col-md-4 control-label">Name</label>
                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control" name="name"
                                           value="{{ $user->name }}" required autofocus>

                                    @if ($errors->has('name'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                                <label for="email" class="col-md-4 control-label">E-Mail Address</label>

                                <div class="col-md-6">
                                    <input id="email" type="email" class="form-control" name="email"
                                           value="{{ $user->email }}" required>

                                    @if ($errors->has('email'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('last_password') ? ' has-error' : '' }}">
                                <label for="last_password" class="col-md-4 control-label">Last Password</label>

                                <div class="col-md-6">
                                    <input id="password" type="password" class="form-control" name="last_password"
                                           required>

                                    @if ($errors->has('password'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('last_password') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                                <label for="password" class="col-md-4 control-label">New Password</label>

                                <div class="col-md-6">
                                    <input id="password" type="password" class="form-control" name="password" >

                                    @if ($errors->has('password'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="password-confirm" class="col-md-4 control-label">Confirm New
                                    Password</label>

                                <div class="col-md-6">
                                    <input id="password-confirm" type="password" class="form-control"
                                           name="password_confirmation" >
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="gender" class="col-md-4 control-label">Gender</label>

                                <div class="col-md-6">
                                    <select name="gender" id="gender" class="form-control">
                                        <option value="male">Male</option>
                                        <option value="female">Female</option>
                                    </select>
                                </div>
                            </div>

                            {{--<div class="form-group">
                                <label for="birthday" class="col-md-4 control-label">Birthday</label>

                                <div class="col-md-6">
                                    <input type="date" name="birthday" id="birthday" class="form-control"
                                           value="{{ $user->birthday }}"
                                           required autofocus>
                                    @if ($errors->has('birthday'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('birthday') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>--}}

                            <div class="form-group">
                                <label for="role" class="col-md-4 control-label">Role</label>

                                <div class="col-md-6">
                                    <select name="role" id="role" class="form-control">
                                        <option value="listner">Listner</option>
                                        <option value="artist">Artist</option>
                                        <option value="produser">Produser</option>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('country') ? ' has-error' : '' }}">
                                <label for="country" class="col-md-4 control-label">Country</label>

                                <div class="col-md-6">
                                    <input id="country" type="text" class="form-control" name="country"
                                           value="{{$user->country}}" required autofocus>

                                    @if ($errors->has('country'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('country') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('country') ? ' has-error' : '' }}">
                                <label for="state" class="col-md-4 control-label">State</label>

                                <div class="col-md-6">
                                    <input id="state" type="text" class="form-control" name="state"
                                           value="{{ $user->state }}" required autofocus>

                                    @if ($errors->has('state'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('state') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('city') ? ' has-error' : '' }}">
                                <label for="city" class="col-md-4 control-label">City</label>

                                <div class="col-md-6">
                                    <input id="city" type="text" class="form-control" name="city"
                                           value="{{ $user->city }}" required autofocus>

                                    @if ($errors->has('city'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('city') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('address') ? ' has-error' : '' }}">
                                <label for="address" class="col-md-4 control-label">Address</label>

                                <div class="col-md-6">
                                    <input id="address" type="text" class="form-control" name="address"
                                           value="{{ $user->address }}" required autofocus>

                                    @if ($errors->has('address'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('address') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>


                            <div class="form-group{{ $errors->has('twitter') ? ' has-error' : '' }}">
                                <label for="twitter" class="col-md-4 control-label">Twitter</label>

                                <div class="col-md-6">
                                    <input id="twitter" type="text" class="form-control" name="twitter"
                                           value="{{ $user->twitter }}">

                                    @if ($errors->has('twitter'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('twitter') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>


                            <div class="form-group{{ $errors->has('facebook') ? ' has-error' : '' }}">
                                <label for="facebook" class="col-md-4 control-label">Facebook</label>

                                <div class="col-md-6">
                                    <input id="facebook" type="text" class="form-control" name="facebook"
                                           value="{{ $user->facebook }}">

                                    @if ($errors->has('facebook'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('facebook') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>


                            <div class="form-group{{ $errors->has('instagram') ? ' has-error' : '' }}">
                                <label for="instagram" class="col-md-4 control-label">Instagram</label>

                                <div class="col-md-6">
                                    <input id="instagram" type="text" class="form-control" name="instagram"
                                           value="{{ $user->instagram }}">

                                    @if ($errors->has('instagram'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('instagram') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            {{--  <div class="col-md-6">
                                  <input id="birt" type="text" class="form-control" name="birt"
                                         value="{{ $user->birthday}}">

                                  @if ($errors->has('birt'))
                                      <span class="help-block">
                                      <strong>{{ $errors->first('birt') }}</strong>
                                  </span>
                                  @endif
                              </div>--}}

                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        Edit
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div class="panel panel-default">
          <div class="panel-heading">Artists</div>

          <div class="panel-body">
            @foreach($users as $user)
              <h1><a href="/users/{{ $user->id }}">{{ $user->name }}</a></h1>
              @if($user->role == 'artist')
                <small>media count {{ $user->media_count }}</small>
              @endif
              <p>followers count: {{ $user->followers_count }}</p>
            @endforeach
          </div>
          {{ $users->links() }}
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/users/messages.blade.php
@extends('layouts.app')

@section('content')
  <div class="container page page-chart">
    <div class="row">
      <div class="col-md-12">
        <div class="title-page">
          MESSAGES
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <table class="chart">
          @foreach($messages as $item)
            <tr>
              <td class="">
                <div class="chart-index">
                </div>
              <td>
                <img class="chart-avatar" src="http://placehold.it/90x90" alt="">
              </td>
              <td>
                <h2>{{ Html::link('/users/' . $item->recive_id, $item->recive_name)}}</h2>
                @if ($item->count_not_read)
                  new message
                @endif
              </td>
              <td>
                <a class="btn btn-default btn-action" href="">New message</a>
              </td>
            </tr>
          @endforeach
        </table>
      </div>

    </div>
    {{--<div class="row"> {{ $messages->links() }} </div>--}}
  </div>

@endsection

resources/views/users/show.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="row">
      @include('includes.auth-userdata')
      <div class="col-md-8">
        @include('includes.tab-menu')
        <form action="/users/{{ $user->id }}/send-message" method="post" style="margin: 10px 0;">
          {{ csrf_field() }}
          <textarea name="text" class="form-control border-radius-0" style="margin: 10px 0;"></textarea>
          <button class="btn btn-default btn-action">Send</button>
        </form>
        @foreach($messages as $message)
          <div class="@if($message->pivot->sender_id == Auth::user()->id) alert-success @else alert-danger @endif"  style="padding: 10px;">
            @if($message->pivot->sender_id == Auth::user()->id)
              {{ Auth::user()->name }} : <br>
            @else
              {{ $user->name }} : <br>
            @endif
            {{ $message->pivot->text }} <br> {{ $message->pivot->created_at }}
          </div>
          <hr>
        @endforeach
      </div>
    </div>
  </div>
@endsection