routes/web.php
<?php

Route::get('media/genre/{id}', 'GenreController@products');
Route::get('artists', 'UserController@artists');
Route::get('produsers', 'UserController@produsers');
Route::get('top-voters', 'UserController@topVoters');
Route::get('media', 'MediaController@index');
Route::get('/', 'MediaController@index');
Auth::routes();
Route::get('search', 'UserController@search');
Route::get('media-search', 'MediaController@search');
Route::get('likes', 'MediaController@likes');
Route::post('edit', 'UserController@edit');
Route::get('edit', 'UserController@editProfile');

Route::group(['middleware' => 'auth'], function () {
    Route::get('favorites', 'UserController@favoritesList');
    Route::get('users/{id}', 'UserController@show');
    Route::get('my-account', 'UserController@myAccount');
    Route::get('activity', 'UserController@activity');
    Route::get('media/create', 'MediaController@create');
    Route::get('media/{media}/edit', 'MediaController@edit');
    Route::post('media', 'MediaController@store');
    Route::patch('media/{media}', 'MediaController@update');
    Route::delete('media/{media}', 'MediaController@destroy');
    Route::get('my-media', 'UserController@myMedia');
    Route::get('unread', 'UserController@unreadMessage');
    Route::get('{relation}/{id}/{action}', 'UserController@sync');
    Route::post('users/{user}/send-message', 'UserController@sendMessage');

});

Route::get('/avatar', function () {
    return view('/users/avatar');
});


Route::get('media/{id}', 'MediaController@show');

app/Models/User.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\Auth;

class User extends Authenticatable
{
    use Notifiable, SoftDeletes;
    protected $fillable = [
        'name',
        'email',
        'password',
        'gender',
        'birthday',
        'twitter',
        'facebook',
        'instagram',
        'role',
        'country',
        'state',
        'city',
        'address',
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $dates = ['birthday', 'created_at', 'updated_at', 'deleted_at'];

    public function media()
    {
        return $this->hasMany(Media::class);
    }

    public function sender()
    {
        return $this->belongsToMany(User::class, 'messages', 'sender_id', 'resiver_id');
    }

    public function resiver()
    {
        return $this->belongsToMany(User::class, 'messages', 'resiver_id', 'sender_id');
    }

    public function listMessages($user_id)
    {
      return $this->belongsToMany(User::class, 'messages', 'resiver_id', 'sender_id')
        ->orWherePivot('sender_id', '=', $user_id)
        ->orWherePivot('resiver_id', '=', $user_id)
        ->withPivot('text')
        ->groupBy('resiver_id')
        ->withTimestamps();
    }

    public function messages($sender_id, $resiver_id)
    {
        return $this->belongsToMany(User::class, 'messages', 'resiver_id', 'sender_id')
            ->wherePivot('sender_id', '=', $resiver_id)
            ->orWherePivot('resiver_id', '=', $resiver_id)
            ->wherePivot('sender_id', '=', $sender_id)
            ->withPivot('text')
            ->withTimestamps();
    }

    public function updateMessages($resiver_id)
    {
        return $this->belongsToMany(User::class, 'messages', 'sender_id', 'resiver_id')
            ->wherePivot('read_at', '=', null)
            ->updateExistingPivot($resiver_id, ['read_at' => Carbon::now()]);
    }

    public function followers()
    {
        return $this->belongsToMany(User::class, 'followers', 'follower_id', 'following_id');
    }

    public function followingers()
    {
        return $this->belongsToMany(User::class, 'followers', 'following_id', 'follower_id');
    }

    public function votes()
    {
        return $this->belongsToMany(Media::class, 'votes')->withTimestamps()->withPivot('date_likes');
    }

    public function todayVotes()
    {
        return $this->belongsToMany(Media::class, 'votes')->withTimestamps()->withPivot('date_likes')
            ->wherePivot('date_likes', '=', Carbon::now()->format('Y-m-d'));
    }

    public function favorites()
    {
        return $this->belongsToMany(Media::class, 'favorites');
    }

    public function scopeEntity($q, string $entity)
    {
        if ($entity == 'artists') {
            return $this->scopeArtists($q);
        }
        return $this->scopeProdusers($q);
    }

    private function scopeArtists($q)
    {
        return $q->whereRole('artist')->withCount('media')->withCount('followers');
    }

    private function scopeProdusers($q)
    {
        return $q->whereRole('produser')->withCount('media')->withCount('followers');
    }
}

app/Http/Controllers/GenreController.php
<?php

namespace App\Http\Controllers;

use App\Models\Genre;

class GenreController extends Controller
{
    public function products(int $id)
    {
        $media = Genre::query()->find($id)->media()->withCount('votes')->paginate(6);
        $genre = Genre::query()->pluck('name', 'id');
        return view('media.index', compact('media', 'genre'));
    }
}

resources/views/includes/auth-userdata.blade.php
<div class="col-md-4">
  <div class="user-avatar">
    <?php $user = Auth::user()?>
    @if ($user->avatar)
        {{--<img src="storage/app/public/avatar/{{ $user->avatar }}">--}}
      @else
{{--<p>kokokoko</p>--}}
    @endif
  </div>
  <div class="col-xs-6">
    <div class="user-name">{{ $user->name }}</div>
    <div class="user-speciality">{{ $user->role }}</div>
  </div>
  <div class="col-xs-6">

    @if(Auth::user()->id != $user->id)
      <?php $follow = Auth::user()->followingers()->pluck('id')->toArray() ?>
      @if(!in_array($user->id, $follow))
        <a class="btn btn-default follow btn-action" href="/followingers/{{ $user->id }}/attach">
          <span><i class="glyphicon glyphicon-user" aria-hidden="true"></i> Follow</span>
        </a>
      @else
        <a class="btn btn-default follow" href="/followingers/{{ $user->id }}/detach">
          <span><i class="glyphicon glyphicon-user" aria-hidden="true"></i> Unfollow</span>
        </a>
      @endif
    @endif


    {{--<button type="button" class="btn btn-default btn-lg follow">--}}
    {{--<span class="glyphicon glyphicon-user" aria-hidden="true"><b> Follow</b></span>--}}
    {{--</button>--}}
  </div>

  <div class="col-xs-12">
    <div class="user-info">
      <div class="user-account-type"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>
        <div>STAFF</div>
      </div>
      <div class="user-marker-map"><span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>
        <div>{{ $user->country }}, {{ $user->state }}, {{ $user->city }}</div>
      </div>
      <div class="user-email"><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
        {{ $user->email }}
      </div>

      @if($user->twitter != null)
        <div class="user-link"><span class="glyphicon glyphicon-link" aria-hidden="true"></span>
          {{ Html::link($user->twitter)}}
        </div>
      @endif
      @if($user->instagram != null)
        <div class="user-link"><span class="glyphicon glyphicon-link" aria-hidden="true"></span>
          {{ Html::link($user->instagram)}}
        </div>
      @endif
      @if($user->facebook != null)
        <div class="user-link"><span class="glyphicon glyphicon-link" aria-hidden="true"></span>
          {{ Html::link($user->facebook)}}
        </div>
      @endif
      <div class="user-joined"><span class="glyphicon glyphicon-time" aria-hidden="true"></span>
        <div>Joined on {{ date_format($user->created_at, 'M j, Y') }}</div>
      </div>
    </div>
  </div>
  <div class="col-xs-12">
    <div class="user-followers">
      <div class="col-xs-4">
        <span>{{ $user->followers_count }}</span><br/>
        <p>followers</p>
      </div>
      <div class="col-xs-4">
        <span>{{ $user->followingers_count }}</span><br/>
        <p>following</p>
      </div>
      <div class="col-xs-4">
        <span>{{ $user->votes_count }}</span><br/>
        <p>votes</p>
      </div>
    </div>
  </div>

</div>

resources/views/includes/menu.blade.php
<header role="header">
  <div class="container">
    <div class="col">
      <div class="col-md-12 bg-black">
        <div class="row">
          <div class="col-md-2 logo"></div>
          <div class="col-md-10 nav-header">
            <ul class="nav navbar-nav nav-link">
              <li>{{ Html::link('/media/create', 'SUBMIT SONG', ['class'=> Request::is('media/create') ? 'active' : ''])}}</li>
              <li>{{ Html::link('/unread', 'MESSAGES', ['class'=> Request::is('unread') ? 'active' : ''])}}</li>
              <li>{{ Html::link('/media', 'CHARTS', ['class'=> Request::is('media') ? 'active' : ''])}}</li>
              <li>{{ Html::link('/top-voters', 'FAVORITES', ['class'=> Request::is('top-voters') ? 'active' : ''])}}</li>
              <li>{{ Html::link('/', 'MAIN SITE', ['class'=> Request::is('/') ? 'active' : ''])}}</li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="/search">
              <div class="form-group">
                <input type="text" class="form-control input" placeholder="author/produser search" name="search">
              </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
              @if (Auth::guest())
                <li><a href="{{ route('login') }}">Login</a></li>
                <li><a href="{{ route('register') }}">Register</a></li>
              @else
                <li class="dropdown nav-link">
                  <a href="#" class="dropdown-toggle " data-toggle="dropdown" role="button" aria-haspopup="true"
                     aria-expanded="false">
                    <div class="small-avatar"><img src="/img/avatar-1.jpg" alt=""></div>
                    {{ Auth::user()->name }}
                    <span class="caret"></span></a>
                  <ul class="dropdown-menu border-radius-0">
                    <li>{{ Html::link('/my-account', 'My account')}}</li>
                    <li>{{ Html::link('/favorites', 'Favorites')}}</li>
                    <li>{{ Html::link('/my-media', 'My medias')}}</li>
                    <li>{{ Html::link('/edit', 'Edit Profile')}}</li>
                    <li role="separator" class="divider"></li>
                    <li><a href="{{ route('logout') }}"
                           onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                        Logout
                      </a></li>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST"
                          style="display: none;">
                      {{ csrf_field() }}
                    </form>
                  </ul>
                </li>
              @endif
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>
</header>

resources/views/includes/tab-menu.blade.php
<ul class="nav nav-tabs user-tab">
  <li class="@if (Request::is('my-account')) active @endif" ><a href="/my-account">Chart que</a></li>
  <li class="@if (Request::is('activity')) active @endif"><a href="/activity">Activity</a></li>
  <li class="@if (Request::is('media/create')) active @endif"><a href="/media/create">Add media</a></li>
  <li class="@if (Request::is('my-media')) active @endif"><a href="/my-media">My media</a></li>
</ul>